### ISSUE TITLE
find()

### ISSUE THREAD

**Issue by ThiagoMiranda** [sergeyksv/tungus#1]
Hi
 I'm having a problem with the find() method.
```javascript
collection.find({}, function(err, items){})  
```
is not returning the items. But
```javascript
findOne({name: "test"}, function(err, item){})
```
 is working just fine. Can you help me?
Thanks

**Comment by dottodot** [comment]
I'm having the same issue, find doesn't seem to work

**Comment by sergeyksv** [comment]
Works now
