### ISSUE TITLE
var tungus = require('tungus');

### ISSUE THREAD

**Issue by gentlecolder** [sergeyksv/tungus#13]
in  your example, you even didnot use the var tungus? why??

**Comment by sergeyksv** [comment]
The goal of require is to allow tungus module to define some global variable to "register" itself as a driver for mongoose. Check this https://github.com/sergeyksv/tungus/blob/master/index.js

**Comment by gentlecolder** [comment]
does that means suport mongoos schema

**Comment by sergeyksv** [comment]
Yes
